--- Running DataFrame.where#39NN/whereNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'DataFrame.where#39NN'), ('notebook', 'whereNN'), ('text', '  File "whereNN.py", line 3, in <module>\n    s.where(s > 0, axis=None, errors=\'raise\', level=None, other=False, inplace=False)\nTypeError: where() got an unexpected keyword argument \'errors\'\n')])
  File "whereNN.py", line 3, in <module>
Error inducing API short name: where, line no: 3
Error inducing API fqn: UNKNOWN, line no: 3
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: []
Prev Params: None
Prev Repair Action: None
Line No: 3
Prev Line No: 0
GitHub Candidates:
[]
KP:[]
EXPP: []
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.613s
user	0m1.497s
sys	0m4.617s
