--- Running testing.assert_index_equal#48NN/assert_index_equalNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'testing.assert_index_equal#48NN'), ('notebook', 'assert_index_equalNN'), ('text', '  File "assert_index_equalNN.py", line 5, in <module>\n    tm.assert_index_equal(a,  b,  \'equiv\',  True, check_less_precise=False, check_exact=True, check_categorical=True, check_order=True, rtol=1e-05)\nTypeError: assert_index_equal() got an unexpected keyword argument \'check_less_precise\'\n')])
  File "assert_index_equalNN.py", line 5, in <module>
Error inducing API short name: assert_index_equal, line no: 5
Error inducing API fqn: pandas.testing.assert_index_equal, line no: 5
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'check_less_precise', 'check_exact', 'check_categorical', 'check_order', 'rtol']
Prev Params: None
Prev Repair Action: None
Line No: 5
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'check_less_precise', 'check_exact', 'check_categorical', 'check_order', 'rtol']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'check_less_precise', 'check_exact', 'check_categorical', 'check_order', 'rtol']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.643s
user	0m1.624s
sys	0m5.663s
