--- Running Series.mask#16NN/maskNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'Series.mask#16NN'), ('notebook', 'maskNN'), ('text', '  File "maskNN.py", line 4, in <module>\n    s.mask(try_cast=False, cond=s > 0)\nTypeError: mask() got an unexpected keyword argument \'try_cast\'\n')])
  File "maskNN.py", line 4, in <module>
Error inducing API short name: mask, line no: 4
Error inducing API fqn: UNKNOWN, line no: 4
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: []
Prev Params: None
Prev Repair Action: None
Line No: 4
Prev Line No: 0
GitHub Candidates:
[]
KP:[]
EXPP: []
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.611s
user	0m1.522s
sys	0m5.238s
