--- Running linear_model.lasso_path#89NN/lasso_pathNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'linear_model.lasso_path#89NN'), ('notebook', 'lasso_pathNN'), ('text', '  File "lasso_pathNN.py", line 5, in <module>\n    coef_path = lasso_path(X,  y,  0.001,  100,  [5.0, 1.0, 0.5],  \'auto\',  None,  None,  None,  True,  None,  False,  False)\nTypeError: lasso_path() takes from 2 to 12 positional arguments but 13 were given\n')])
  File "lasso_pathNN.py", line 5, in <module>
Error inducing API short name: lasso_path, line no: 5
Error inducing API fqn: sklearn.linear_model.lasso_path, line no: 5
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5', 'IMPLICIT_6', 'IMPLICIT_7', 'IMPLICIT_8', 'IMPLICIT_9', 'IMPLICIT_10', 'IMPLICIT_11', 'IMPLICIT_12']
Prev Params: None
Prev Repair Action: None
Line No: 5
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5', 'IMPLICIT_6', 'IMPLICIT_7', 'IMPLICIT_8', 'IMPLICIT_9', 'IMPLICIT_10', 'IMPLICIT_11', 'IMPLICIT_12']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5', 'IMPLICIT_6', 'IMPLICIT_7', 'IMPLICIT_8', 'IMPLICIT_9', 'IMPLICIT_10', 'IMPLICIT_11', 'IMPLICIT_12']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.873s
user	0m3.995s
sys	0m13.313s
