--- Running numpy.histogram2d#28NN/histogram2dNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'numpy.histogram2d#28NN'), ('notebook', 'histogram2dNN'), ('text', '  File "histogram2dNN.py", line 4, in <module>\n    (hist, x_edges, y_edges) = np.histogram2d(x,  y,  10,  [[-2, 2], [-2, 2]],  True, weights=x + y, density=None)\n  File "<__array_function__ internals>", line 198, in histogram2d\nTypeError: histogram2d() got multiple values for argument \'density\'\n')])
  File "histogram2dNN.py", line 4, in <module>
Error inducing API short name: , line no: 4
Error inducing API fqn: numpy.histogram2d, line no: 4
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'weights', 'density']
Prev Params: None
Prev Repair Action: None
Line No: 4
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'weights', 'density']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'weights', 'density']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m1.430s
user	0m1.220s
sys	0m4.145s
