--- Running core.arrays.SparseArray#14NN/SparseArrayNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'core.arrays.SparseArray#14NN'), ('notebook', 'SparseArrayNN'), ('text', '  File "SparseArrayNN.py", line 2, in <module>\n    arr = SparseArray(data=[0, 0, 1, 2], sparse_index=None, index=None, fill_value=None)\nTypeError: __init__() got an unexpected keyword argument \'index\'\n')])
  File "SparseArrayNN.py", line 2, in <module>
Error inducing API short name: SparseArray, line no: 2
Error inducing API fqn: pandas.arrays.SparseArray, line no: 2
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['data', 'sparse_index', 'index', 'fill_value']
Prev Params: None
Prev Repair Action: None
Line No: 2
Prev Line No: 0
GitHub Candidates:
[]
KP:['data', 'sparse_index', 'index', 'fill_value']
EXPP: ['data', 'sparse_index', 'index', 'fill_value']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.578s
user	0m1.559s
sys	0m5.195s
