tm.assert_index_equal(a, b, 'equiv', True, False, True, True, True, rtol=1e-05, atol=1e-08, obj='Index'), Failed to load pkl in target version2.0.0: Traceback (most recent call last):
  File "dynamicMatch.py", line 162, in <module>
    paraValueDict=dill.load(fr)
  File "/dataset/zhang/anaconda3/envs/pandas2.0.0/lib/python3.8/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/dataset/zhang/anaconda3/envs/pandas2.0.0/lib/python3.8/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
  File "/dataset/zhang/anaconda3/envs/pandas2.0.0/lib/python3.8/site-packages/dill/_dill.py", line 432, in find_class
    return StockUnpickler.find_class(self, module, name)
ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'

[2.0.0]tm.assert_index_equal(a, b, 'equiv', True, False, True, True, True, rtol=1e-05, atol=1e-08, obj='Index'), generate new pkl failed: Traceback (most recent call last):
  File "assert_index_equalNN.py", line 9, in <module>
    tm.assert_index_equal(a, b, 'equiv', True, False, True, True, True, rtol=1e-05, atol=1e-08, obj='Index')
TypeError: assert_index_equal() got multiple values for argument 'rtol'

tm.assert_index_equal(a, b, 'equiv', True, False, True, True, True, rtol=1e-05, atol=1e-08, obj='Index'), validate error: Traceback (most recent call last):
  File "verifySingle.py", line 10, in <module>
    paraValueDict=dill.load(fr)
  File "/dataset/zhang/anaconda3/envs/pandas2.0.0/lib/python3.8/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/dataset/zhang/anaconda3/envs/pandas2.0.0/lib/python3.8/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
  File "/dataset/zhang/anaconda3/envs/pandas2.0.0/lib/python3.8/site-packages/dill/_dill.py", line 432, in find_class
    return StockUnpickler.find_class(self, module, name)
ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'


