--- Running scipy.linalg.solve_triangular#41NN/solve_triangularNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'scipy.linalg.solve_triangular#41NN'), ('notebook', 'solve_triangularNN'), ('text', '  File "solve_triangularNN.py", line 5, in <module>\n    x = solve_triangular(a, b=b, trans=0, lower=True, unit_diagonal=True, overwrite_b=True, debug=None, check_finite=True)\nTypeError: solve_triangular() got an unexpected keyword argument \'debug\'\n')])
  File "solve_triangularNN.py", line 5, in <module>
Error inducing API short name: solve_triangular, line no: 5
Error inducing API fqn: scipy.linalg.solve_triangular, line no: 5
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'b', 'trans', 'lower', 'unit_diagonal', 'overwrite_b', 'debug', 'check_finite']
Prev Params: None
Prev Repair Action: None
Line No: 5
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'b', 'trans', 'lower', 'unit_diagonal', 'overwrite_b', 'debug', 'check_finite']
EXPP: ['IMPLICIT_0', 'b', 'trans', 'lower', 'unit_diagonal', 'overwrite_b', 'debug', 'check_finite']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.528s
user	0m2.137s
sys	0m8.093s
