--- Running plotly.express.histogram#303NN/histogramNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'plotly.express.histogram#303NN'), ('notebook', 'histogramNN'), ('text', '  File "histogramNN.py", line 3, in <module>\n    fig = px.histogram(df,  \'total_bill\',  None,  None,  None,  None,  None,  None,  None,  None,  {},  {},  None,  {},  None,  None,  \'v\',  \'relative\',  None,  None,  False,  False, range_x=None, range_y=None)\n  File "/dataset/zhang/anaconda3/envs/Rplotly4.3.0/lib/python3.6/site-packages/plotly/express/_chart_types.py", line 372, in histogram\n    layout_patch=dict(barmode=barmode, barnorm=barnorm),\n  File "/dataset/zhang/anaconda3/envs/Rplotly4.3.0/lib/python3.6/site-packages/plotly/express/_core.py", line 1095, in make_figure\n    args, constructor, trace_patch\n  File "/dataset/zhang/anaconda3/envs/Rplotly4.3.0/lib/python3.6/site-packages/plotly/express/_core.py", line 971, in infer_config\n    args = build_dataframe(args, all_attrables, array_attrables)\n  File "/dataset/zhang/anaconda3/envs/Rplotly4.3.0/lib/python3.6/site-packages/plotly/express/_core.py", line 940, in build_dataframe\n    % (field, len(argument), str(list(df_output.columns)), length)\nValueError: All arguments should have the same length. The length of argument `animation_group` is 0, whereas the length of previous arguments [\'total_bill\'] is 244\n')])
  File "histogramNN.py", line 3, in <module>
Error inducing API short name: histogram, line no: 3
Error inducing API fqn: plotly.express.histogram, line no: 3
*** ValueError: PLACEHOLDER
All known params: []
All known params' names: []
Error line tokens: ['valueerror', 'placeholder']
Repair Action: arg_value
Key Params: []
Prev Params: None
Prev Repair Action: None
Line No: 3
Prev Line No: 0
GitHub Candidates:
[]
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m1.185s
user	0m2.161s
sys	0m5.581s
