--- Running Series.mask#15NN/maskNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'Series.mask#15NN'), ('notebook', 'maskNN'), ('text', '  File "maskNN.py", line 4, in <module>\n    s.mask(cond=s > 0, errors=\'raise\')\nTypeError: mask() got an unexpected keyword argument \'errors\'\n')])
  File "maskNN.py", line 4, in <module>
Error inducing API short name: mask, line no: 4
Error inducing API fqn: UNKNOWN, line no: 4
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: []
Prev Params: None
Prev Repair Action: None
Line No: 4
Prev Line No: 0
GitHub Candidates:
[]
KP:[]
EXPP: []
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.632s
user	0m1.524s
sys	0m4.426s
