--- Running Timestamp.fromordinal#6NN/fromordinalNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'Timestamp.fromordinal#6NN'), ('notebook', 'fromordinalNN'), ('text', '  File "fromordinalNN.py", line 2, in <module>\n    pd.Timestamp.fromordinal(737425,  None,  None)\n  File "pandas/_libs/tslibs/timestamps.pyx", line 1343, in pandas._libs.tslibs.timestamps.Timestamp.fromordinal\nTypeError: fromordinal() takes at most 3 positional arguments (4 given)\n')])
  File "fromordinalNN.py", line 2, in <module>
Error inducing API short name: fromordinal, line no: 2
Error inducing API fqn: pandas.Timestamp.fromordinal, line no: 2
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2']
Prev Params: None
Prev Repair Action: None
Line No: 2
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.622s
user	0m1.662s
sys	0m6.354s
