--- Running scipy.linalg.solve#43NN/solveNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'scipy.linalg.solve#43NN'), ('notebook', 'solveNN'), ('text', '  File "/home/zhang/CC/Python/RepairTool/ToolCompare/relancer/relancer-exp/fixed_notebooks/relancer/scipy.linalg.solve#43NN/solveNN.py", line 4, in <module>\n    x = scipy.linalg.solve(a,  b,  False,  False,  False,  False,  True,  \'gen\',  False)\nTypeError: solve() takes from 2 to 8 positional arguments but 9 were given\n')])
  File "/home/zhang/CC/Python/RepairTool/ToolCompare/relancer/relancer-exp/fixed_notebooks/relancer/scipy.linalg.solve#43NN/solveNN.py", line 4, in <module>
Error inducing API short name: solve, line no: 4
Error inducing API fqn: scipy.linalg.solve, line no: 4
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5', 'IMPLICIT_6', 'IMPLICIT_7', 'IMPLICIT_8']
Prev Params: None
Prev Repair Action: None
Line No: 4
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5', 'IMPLICIT_6', 'IMPLICIT_7', 'IMPLICIT_8']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5', 'IMPLICIT_6', 'IMPLICIT_7', 'IMPLICIT_8']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.513s
user	0m2.087s
sys	0m8.240s
