--- Running testing.assert_series_equal#190NN/assert_series_equalNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'testing.assert_series_equal#190NN'), ('notebook', 'assert_series_equalNN'), ('text', '  File "assert_series_equalNN.py", line 5, in <module>\n    tm.assert_series_equal(a,  b,  True,  \'equiv\', check_datetimelike_compat=False, check_index=True, check_less_precise=False, check_exact=False, check_names=True, check_series_type=True)\nTypeError: assert_series_equal() got an unexpected keyword argument \'check_less_precise\'\n')])
  File "assert_series_equalNN.py", line 5, in <module>
Error inducing API short name: assert_series_equal, line no: 5
Error inducing API fqn: pandas.testing.assert_series_equal, line no: 5
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'check_datetimelike_compat', 'check_index', 'check_less_precise', 'check_exact', 'check_names', 'check_series_type']
Prev Params: None
Prev Repair Action: None
Line No: 5
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'check_datetimelike_compat', 'check_index', 'check_less_precise', 'check_exact', 'check_names', 'check_series_type']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'check_datetimelike_compat', 'check_index', 'check_less_precise', 'check_exact', 'check_names', 'check_series_type']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.639s
user	0m1.725s
sys	0m5.839s
