--- Running testing.assert_series_equal#240NN/assert_series_equalNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'testing.assert_series_equal#240NN'), ('notebook', 'assert_series_equalNN'), ('text', '  File "assert_series_equalNN.py", line 5, in <module>\n    tm.assert_series_equal(a,  b,  True, check_names=True, check_series_type=True, check_index=True, check_less_precise=False, check_index_type=\'equiv\', check_datetimelike_compat=False, check_categorical=True, check_like=False, check_exact=False)\nTypeError: assert_series_equal() got an unexpected keyword argument \'check_less_precise\'\n')])
  File "assert_series_equalNN.py", line 5, in <module>
Error inducing API short name: assert_series_equal, line no: 5
Error inducing API fqn: pandas.testing.assert_series_equal, line no: 5
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'check_names', 'check_series_type', 'check_index', 'check_less_precise', 'check_index_type', 'check_datetimelike_compat', 'check_categorical', 'check_like', 'check_exact']
Prev Params: None
Prev Repair Action: None
Line No: 5
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'check_names', 'check_series_type', 'check_index', 'check_less_precise', 'check_index_type', 'check_datetimelike_compat', 'check_categorical', 'check_like', 'check_exact']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'check_names', 'check_series_type', 'check_index', 'check_less_precise', 'check_index_type', 'check_datetimelike_compat', 'check_categorical', 'check_like', 'check_exact']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.615s
user	0m1.570s
sys	0m5.367s
