--- Running scipy.sparse.linalg.cgs#30NN/cgsNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'scipy.sparse.linalg.cgs#30NN'), ('notebook', 'cgsNN'), ('text', '  File "cgsNN.py", line 6, in <module>\n    (x, info) = cgs(A,  b,  None, tol=1e-05, maxiter=100, xtype=None, M=None)\nTypeError: cgs() got an unexpected keyword argument \'xtype\'\n')])
  File "cgsNN.py", line 6, in <module>
Error inducing API short name: , line no: 6
Error inducing API fqn: scipy.sparse.linalg.cgs, line no: 6
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'tol', 'maxiter', 'xtype', 'M']
Prev Params: None
Prev Repair Action: None
Line No: 6
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'tol', 'maxiter', 'xtype', 'M']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'tol', 'maxiter', 'xtype', 'M']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.518s
user	0m1.645s
sys	0m5.218s
