--- Running DataFrame.to_latex#234NN/to_latexNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'DataFrame.to_latex#234NN'), ('notebook', 'to_latexNN'), ('text', '  File "to_latexNN.py", line 3, in <module>\n    print(df.to_latex(None,  None,  None,  True,  True,  \'NaN\',  None,  None,  None,  True,  False,  None,  None,  None,  None,  \'.\',  None,  None,  None, caption=None, label=None))\nTypeError: to_latex() got multiple values for argument \'caption\'\n')])
  File "to_latexNN.py", line 3, in <module>
Error inducing API short name: to_latex, line no: 3
Error inducing API fqn: UNKNOWN, line no: 3
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: []
Prev Params: None
Prev Repair Action: None
Line No: 3
Prev Line No: 0
GitHub Candidates:
[]
KP:[]
EXPP: []
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.640s
user	0m1.567s
sys	0m5.246s
